services:
  - type: pserv
    name: user-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: user-service
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3001"
      - key: JWT_SECRET
        generateValue: true

  - type: pserv
    name: product-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: product-service
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3002"

  - type: pserv
    name: cart-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: cart-service
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3003"

  - type: pserv
    name: order-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: order-service
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3004"

  - type: pserv
    name: serverless-webhook
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: serverless
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "5001"

  - type: pserv
    name: payment-service
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: payment-service
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "3005"
      - key: SERVERLESS_URL
        value: http://serverless-webhook:5001/ecommerce/us-central1/paymentWebhook

  - type: web
    name: api-gateway
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: api-gateway
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "8080"
      - key: USER_SERVICE_URL
        value: http://user-service:3001
      - key: PRODUCT_SERVICE_URL
        value: http://product-service:3002
      - key: CART_SERVICE_URL
        value: http://cart-service:3003
      - key: ORDER_SERVICE_URL
        value: http://order-service:3004
      - key: PAYMENT_SERVICE_URL
        value: http://payment-service:3005

  - type: web
    name: frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: frontend
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_URL
        sync: false
